/**
 * Utils barrel export
 */
export { PATHS, LIMITS, EXTRACTABLE_EXTENSIONS, PLUGIN_META } from "./config.ts";
export {
  log,
  createLogger,
  getLogger,
  createModuleLogger,
  startTimer,
  type LogConfig,
  type LogLevel,
  type LogFields,
  type LogEntry,
} from "./logger.ts";
export {
  extractErrorMessage,
  isFileNotFoundError,
  isPermissionError,
  createContextualError,
  AppError,
  Errors,
  safeExecute,
  safeExecuteSync,
  isRecoverable,
  withRetry,
  type ErrorCode,
  type ErrorSeverity,
  type ErrorCategory,
  type ErrorMetadata,
  type ErrorResult,
  type RetryConfig,
} from "./errors.ts";
export {
  output,
  createFormatter,
  formatBytes,
  formatDuration,
  formatRelativeTime,
  formatNumber,
  formatPercent,
  OutputFormatter,
  type OutputStyle,
  type ColorName,
} from "./output.ts";
export {
  ProgressNotifier,
  getNotifier,
  createNotifier,
  showProgress,
  showStatus,
  withProgress,
  type TaskStatus,
  type NotificationType,
  type ProgressInfo,
  type NotificationConfig,
  type ProgressCallback,
} from "./notifications.ts";
export {
  InteractiveWizard,
  createWizard,
  promptText,
  promptConfirm,
  promptSelect,
  promptMultiselect,
  promptNumber,
  type StepType,
  type WizardStep,
  type WizardOption,
  type WizardConfig,
  type WizardResult,
} from "./wizard.ts";

// Phase 3: 遥测和工作流
export {
  telemetryEventSchema,
  telemetryConfigSchema,
  trackEvent,
  trackSkillUsage,
  trackAgentUsage,
  trackToolUsage,
  trackSessionStart,
  trackSessionEnd,
  getTelemetryStats,
  saveStats,
  enableTelemetry,
  disableTelemetry,
  isTelemetryEnabled,
  getAnonymousId,
  clearTelemetryData,
  generateTelemetryReport,
  type TelemetryEvent,
  type TelemetryConfig,
} from "./telemetry.ts";
export {
  workflowStepSchema,
  workflowStateSchema,
  WorkflowPersistence,
  workflowPersistence,
  createWorkflow,
  getWorkflow,
  updateWorkflow,
  getWorkflowProgress,
  formatWorkflowStatus,
  type WorkflowStep,
  type WorkflowState,
  type WorkflowStatus,
  type StepStatus,
} from "./workflow-persistence.ts";
